### ISSUE TITLE
Exception encountered on using TOKENS_ENABLE_MOCK as true 

### ISSUE THREAD

**Issue by vibhory2j** [zalando-stups/spring-boot-zalando-stups-tokens#33]
An exception is encountered on starting zmon controller with mock tokens. Please see below the exception encountered.

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-09-22 14:24:13.866 ERROR 10 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'secrets' defined in class path resource [org/zalando/stups/tokens/config/SecretsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.zalando.stups.tokens.Secrets]: Factory method 'secrets' threw exception; nested exception is java.lang.ClassCastException: org.zalando.stups.tokens.config.AccessTokensBeanAutoConfiguration$MockAccessTokensBean$1 cannot be cast to org.zalando.stups.tokens.AbstractAccessTokenRefresher
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372) [spring-boot-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) [spring-boot-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.4.RELEASE.jar!/:1.4.4.RELEASE]
	at org.zalando.zmon.ZmonApplication.main(ZmonApplication.java:17) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [zmon-controller.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [zmon-controller.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [zmon-controller.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [zmon-controller.jar:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.zalando.stups.tokens.Secrets]: Factory method 'secrets' threw exception; nested exception is java.lang.ClassCastException: org.zalando.stups.tokens.config.AccessTokensBeanAutoConfiguration$MockAccessTokensBean$1 cannot be cast to org.zalando.stups.tokens.AbstractAccessTokenRefresher
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	... 26 common frames omitted
Caused by: java.lang.ClassCastException: org.zalando.stups.tokens.config.AccessTokensBeanAutoConfiguration$MockAccessTokensBean$1 cannot be cast to org.zalando.stups.tokens.AbstractAccessTokenRefresher
	at org.zalando.stups.tokens.AccessTokensBean.getDelegate(AccessTokensBean.java:184) ~[tokens-spring-boot-starter-0.11.0-beta-6.jar!/:na]
	at org.zalando.stups.tokens.config.SecretsAutoConfiguration.secrets(SecretsAutoConfiguration.java:24) ~[tokens-spring-boot-starter-0.11.0-beta-6.jar!/:na]
	at org.zalando.stups.tokens.config.SecretsAutoConfiguration$$EnhancerBySpringCGLIB$$49837495.CGLIB$secrets$0(<generated>) ~[tokens-spring-boot-starter-0.11.0-beta-6.jar!/:na]
	at org.zalando.stups.tokens.config.SecretsAutoConfiguration$$EnhancerBySpringCGLIB$$49837495$$FastClassBySpringCGLIB$$e0dd964.invoke(<generated>) ~[tokens-spring-boot-starter-0.11.0-beta-6.jar!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	at org.zalando.stups.tokens.config.SecretsAutoConfiguration$$EnhancerBySpringCGLIB$$49837495.secrets(<generated>) ~[tokens-spring-boot-starter-0.11.0-beta-6.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
	... 27 common frames omitted

**Comment by jbellmann** [comment]
@vibhory2j can you please tell me something about your environment? Are you running on Kubernetes?

**Comment by vibhory2j** [comment]
Yes. We were trying this on kubernetes.

Thanks
Vibhor
